name: Terraform Deploy

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false -var-file="terraform.tfvars"

    - name: Terraform Apply (Manual Approval Required)
      if: github.event_name == 'workflow_dispatch'
      run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"
